[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[build.processing]
  skip_processing = true

[functions]
  included_files = ["node_modules/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 