[build]
  command = "npm run build"
  publish = ".next/standalone"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_BUNDLER = "webpack"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 